"""table Server add column server_ip

Revision ID: 198cd741de8d
Revises: 21d9510134f3
Create Date: 2019-04-11 01:32:13.665837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198cd741de8d'
down_revision = '21d9510134f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('server_ip', sa.VARCHAR(length=255)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'server_ip')
    # ### end Alembic commands ###
