"""empty message

Revision ID: 21d9510134f3
Revises: 
Create Date: 2019-04-09 15:35:27.810001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d9510134f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('database_user', sa.VARCHAR(length=100), nullable=False),
    sa.Column('database_pwd', sa.VARCHAR(length=100), nullable=False),
    sa.Column('database_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('update_counter', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('update_type', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain')
    op.drop_table('servers')
    # ### end Alembic commands ###
